### ISSUE TITLE
Textarea width problem

### ISSUE THREAD

**Issue by iulianrusu** [dhg/Skeleton#148]
Hello! I'm using Skeleton grid system and I don't know where search for this problem. I'm using a textarea with width 100% into a div, but when I settings padding-left or padding-right the width of the text area change. The div is styled by a columns system.
Sorry for my english.
Here I want to explain my problem with some images.
Thanks to everybody 

padding:0; width:100%;
![padding0](https://f.cloud.github.com/assets/6057991/1662421/a462c558-5bfe-11e3-89e8-a720fd272589.png)

padding:10px; width:100%;
![padding10](https://f.cloud.github.com/assets/6057991/1662407/5585cb60-5bfe-11e3-9382-f080a3c3e5e8.png)

**Comment by catalinmiron** [comment]
try this:

``` css
* {
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
```

or directly textarea

``` css
textarea {
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
}
```
