### ISSUE TITLE
Print stylesheet

### ISSUE THREAD

**Issue by hadley** [dhg/Skeleton#58]
Does skeleton need a print stylesheet?  When printing with chrome, content runs off the side of the page.

Including the following fixes the problem:

``` CSS
@media print {
  .container {width: 100%}
  .container .sixteen.columns {width: 100%}
}
```

but that's obviously a crude hack for my special case.
