### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by dcancel** [dhg/Skeleton#90]
Wondering if anyone has come up with an elegant way to display the navigation bar to mobile users?

**Comment by atomicpages** [comment]
I think using a regular menu where you style the list items with a background works out well. See code below:

``` css
ul {
     margin: 0;
     padding: 0;
}
li {
     background: #ccc;
     list-style: none;
     display: list-item; /* only necessary if the li is inheriting display: inline*/
     float: none; /* only necessary is your li is inheriting a float */
     border-top: 1px solid white;
     border-bottom: 1px solid white;
}
/* optional to remove top most and bottom most borders */
li:first-child { border-top: none; }
li:last-child { border-bottom: none; }
li a { color: white; }
li a:hover { color: black; }
```

To see it in action we have something live here: http://atomicpages.org/magesample/
